# Generated by Django 2.2.7 on 2020-07-19 21:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='Seller First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Seller Last Name')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('client_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
